//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xperimen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xperimen.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string app_alert {
            get {
                return ResourceManager.GetString("app_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string app_apr {
            get {
                return ResourceManager.GetString("app_apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string app_aug {
            get {
                return ResourceManager.GetString("app_aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string app_cancel {
            get {
                return ResourceManager.GetString("app_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string app_confirm {
            get {
                return ResourceManager.GetString("app_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Password.
        /// </summary>
        internal static string app_confirmpwd {
            get {
                return ResourceManager.GetString("app_confirmpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string app_dec {
            get {
                return ResourceManager.GetString("app_dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string app_delete {
            get {
                return ResourceManager.GetString("app_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string app_done {
            get {
                return ResourceManager.GetString("app_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string app_empty {
            get {
                return ResourceManager.GetString("app_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string app_error {
            get {
                return ResourceManager.GetString("app_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        internal static string app_exist {
            get {
                return ResourceManager.GetString("app_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string app_failed {
            get {
                return ResourceManager.GetString("app_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string app_feb {
            get {
                return ResourceManager.GetString("app_feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string app_friday {
            get {
                return ResourceManager.GetString("app_friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string app_jan {
            get {
                return ResourceManager.GetString("app_jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string app_jul {
            get {
                return ResourceManager.GetString("app_jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string app_jun {
            get {
                return ResourceManager.GetString("app_jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string app_mar {
            get {
                return ResourceManager.GetString("app_mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string app_may {
            get {
                return ResourceManager.GetString("app_may", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string app_monday {
            get {
                return ResourceManager.GetString("app_monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string app_notfound {
            get {
                return ResourceManager.GetString("app_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Match.
        /// </summary>
        internal static string app_notmatch {
            get {
                return ResourceManager.GetString("app_notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string app_nov {
            get {
                return ResourceManager.GetString("app_nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string app_oct {
            get {
                return ResourceManager.GetString("app_oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string app_okay {
            get {
                return ResourceManager.GetString("app_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string app_permission {
            get {
                return ResourceManager.GetString("app_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string app_saturday {
            get {
                return ResourceManager.GetString("app_saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string app_save {
            get {
                return ResourceManager.GetString("app_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string app_sept {
            get {
                return ResourceManager.GetString("app_sept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string app_success {
            get {
                return ResourceManager.GetString("app_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string app_sunday {
            get {
                return ResourceManager.GetString("app_sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string app_thursday {
            get {
                return ResourceManager.GetString("app_thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string app_tuesday {
            get {
                return ResourceManager.GetString("app_tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string app_unavailable {
            get {
                return ResourceManager.GetString("app_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undone.
        /// </summary>
        internal static string app_undone {
            get {
                return ResourceManager.GetString("app_undone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string app_update {
            get {
                return ResourceManager.GetString("app_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string app_wednesday {
            get {
                return ResourceManager.GetString("app_wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo cancelled..
        /// </summary>
        internal static string camgal_camcancel {
            get {
                return ResourceManager.GetString("camgal_camcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is not available or take photo not supported..
        /// </summary>
        internal static string camgal_camunavailable {
            get {
                return ResourceManager.GetString("camgal_camunavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo selected..
        /// </summary>
        internal static string camgal_nophotoselect {
            get {
                return ResourceManager.GetString("camgal_nophotoselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App required permission to access media gallery to pick photos..
        /// </summary>
        internal static string camgal_permmedia {
            get {
                return ResourceManager.GetString("camgal_permmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App required permission to access photos to pick photos..
        /// </summary>
        internal static string camgal_permphoto {
            get {
                return ResourceManager.GetString("camgal_permphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo gallery is not available to pick photo..
        /// </summary>
        internal static string camgal_photounavailable {
            get {
                return ResourceManager.GetString("camgal_photounavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account and all the data successfully deleted..
        /// </summary>
        internal static string code_setting_allsuccessdelete {
            get {
                return ResourceManager.GetString("code_setting_allsuccessdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted..
        /// </summary>
        internal static string code_setting_deleted {
            get {
                return ResourceManager.GetString("code_setting_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with that username already exist. Please choose a different username..
        /// </summary>
        internal static string code_setting_edyexist {
            get {
                return ResourceManager.GetString("code_setting_edyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error. Failed to delete this account..
        /// </summary>
        internal static string code_setting_faildelete {
            get {
                return ResourceManager.GetString("code_setting_faildelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error. Failed to delete the user..
        /// </summary>
        internal static string code_setting_faildeleteuser {
            get {
                return ResourceManager.GetString("code_setting_faildeleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty. Please insert your first name..
        /// </summary>
        internal static string code_setting_fnameempty {
            get {
                return ResourceManager.GetString("code_setting_fnameempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error. Current login ID not found..
        /// </summary>
        internal static string code_setting_idnotfound {
            get {
                return ResourceManager.GetString("code_setting_idnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty. Please insert your last name..
        /// </summary>
        internal static string code_setting_lnameempty {
            get {
                return ResourceManager.GetString("code_setting_lnameempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current login information not found..
        /// </summary>
        internal static string code_setting_lognotfound {
            get {
                return ResourceManager.GetString("code_setting_lognotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated..
        /// </summary>
        internal static string code_setting_profupdated {
            get {
                return ResourceManager.GetString("code_setting_profupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty. Please insert your password..
        /// </summary>
        internal static string code_setting_pwdempty {
            get {
                return ResourceManager.GetString("code_setting_pwdempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be more than 6 characters..
        /// </summary>
        internal static string code_setting_pwdmore6 {
            get {
                return ResourceManager.GetString("code_setting_pwdmore6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password is not match with current password..
        /// </summary>
        internal static string code_setting_pwdnotmatch {
            get {
                return ResourceManager.GetString("code_setting_pwdnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-type your password..
        /// </summary>
        internal static string code_setting_retypepwd {
            get {
                return ResourceManager.GetString("code_setting_retypepwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you confirm to delete your account ? All data such as commitments and expenses will be deleted..
        /// </summary>
        internal static string code_setting_suredelself {
            get {
                return ResourceManager.GetString("code_setting_suredelself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete .
        /// </summary>
        internal static string code_setting_suredeluser {
            get {
                return ResourceManager.GetString("code_setting_suredeluser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update application theme failed..
        /// </summary>
        internal static string code_setting_themefailed {
            get {
                return ResourceManager.GetString("code_setting_themefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information failed..
        /// </summary>
        internal static string code_setting_updatefailed {
            get {
                return ResourceManager.GetString("code_setting_updatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be more than 6 characters..
        /// </summary>
        internal static string code_setting_usermore6 {
            get {
                return ResourceManager.GetString("code_setting_usermore6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create your username.
        /// </summary>
        internal static string code_setting_username {
            get {
                return ResourceManager.GetString("code_setting_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty. Please insert your username..
        /// </summary>
        internal static string code_setting_usernameempty {
            get {
                return ResourceManager.GetString("code_setting_usernameempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string comm_accno {
            get {
                return ResourceManager.GetString("comm_accno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Commitment.
        /// </summary>
        internal static string comm_addcomm {
            get {
                return ResourceManager.GetString("comm_addcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New commitment added..
        /// </summary>
        internal static string comm_commadded {
            get {
                return ResourceManager.GetString("comm_commadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment deleted..
        /// </summary>
        internal static string comm_commdeleted {
            get {
                return ResourceManager.GetString("comm_commdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congrats ! All commitment(s) are completed for this month.
        /// </summary>
        internal static string comm_congrats {
            get {
                return ResourceManager.GetString("comm_congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        internal static string comm_desc {
            get {
                return ResourceManager.GetString("comm_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details (account number, bank name, etc...).
        /// </summary>
        internal static string comm_descplaceholder {
            get {
                return ResourceManager.GetString("comm_descplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment marked as not done yet..
        /// </summary>
        internal static string comm_detailmarknotdone {
            get {
                return ResourceManager.GetString("comm_detailmarknotdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment marked as paid..
        /// </summary>
        internal static string comm_detailmarkpaid {
            get {
                return ResourceManager.GetString("comm_detailmarkpaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment details updated..
        /// </summary>
        internal static string comm_detailupdated {
            get {
                return ResourceManager.GetString("comm_detailupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error when updating commitment..
        /// </summary>
        internal static string comm_detailupdateerror {
            get {
                return ResourceManager.GetString("comm_detailupdateerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done Paid.
        /// </summary>
        internal static string comm_donepaid {
            get {
                return ResourceManager.GetString("comm_donepaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Commitment.
        /// </summary>
        internal static string comm_editcomm {
            get {
                return ResourceManager.GetString("comm_editcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number  is empty. Please insert account number..
        /// </summary>
        internal static string comm_emptyaccno {
            get {
                return ResourceManager.GetString("comm_emptyaccno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment amount is empty. Please insert commitment amount..
        /// </summary>
        internal static string comm_emptyamount {
            get {
                return ResourceManager.GetString("comm_emptyamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is empty. Please insert any title (bill, rent, investment, etc...).
        /// </summary>
        internal static string comm_emptytitle {
            get {
                return ResourceManager.GetString("comm_emptytitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error adding new commitment..
        /// </summary>
        internal static string comm_erroraddcomm {
            get {
                return ResourceManager.GetString("comm_erroraddcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error deleting the selected commitment..
        /// </summary>
        internal static string comm_errordel {
            get {
                return ResourceManager.GetString("comm_errordel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error retrieving the selected commitment..
        /// </summary>
        internal static string comm_errorgetcomm {
            get {
                return ResourceManager.GetString("comm_errorgetcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error retrieving commitment list..
        /// </summary>
        internal static string comm_errorgetcommlist {
            get {
                return ResourceManager.GetString("comm_errorgetcommlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error updating net balance..
        /// </summary>
        internal static string comm_errorupdnet {
            get {
                return ResourceManager.GetString("comm_errorupdnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Not Done.
        /// </summary>
        internal static string comm_marknotdone {
            get {
                return ResourceManager.GetString("comm_marknotdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment List.
        /// </summary>
        internal static string comm_navtitle {
            get {
                return ResourceManager.GetString("comm_navtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net :.
        /// </summary>
        internal static string comm_net {
            get {
                return ResourceManager.GetString("comm_net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Commitment.
        /// </summary>
        internal static string comm_newcomm {
            get {
                return ResourceManager.GetString("comm_newcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected commitment is not found..
        /// </summary>
        internal static string comm_notfound {
            get {
                return ResourceManager.GetString("comm_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any commitment yet. Click button below to add new commitment..
        /// </summary>
        internal static string comm_notyet {
            get {
                return ResourceManager.GetString("comm_notyet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title (bill, rent, etc...).
        /// </summary>
        internal static string comm_placeholder {
            get {
                return ResourceManager.GetString("comm_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Commitment.
        /// </summary>
        internal static string comm_savecomm {
            get {
                return ResourceManager.GetString("comm_savecomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this commitment ?.
        /// </summary>
        internal static string comm_suredel {
            get {
                return ResourceManager.GetString("comm_suredel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming commitment is.
        /// </summary>
        internal static string comm_upcoming {
            get {
                return ResourceManager.GetString("comm_upcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        internal static string comm_youhave {
            get {
                return ResourceManager.GetString("comm_youhave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commitment(s) not yet done.
        /// </summary>
        internal static string comm_youhave2 {
            get {
                return ResourceManager.GetString("comm_youhave2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for this month.
        /// </summary>
        internal static string comm_youhave3 {
            get {
                return ResourceManager.GetString("comm_youhave3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string dashboard_available {
            get {
                return ResourceManager.GetString("dashboard_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update expenses in the left side menu button.
        /// </summary>
        internal static string dashboard_editexp {
            get {
                return ResourceManager.GetString("dashboard_editexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses amount is empty. Please insert expenses amount..
        /// </summary>
        internal static string dashboard_emptyexp {
            get {
                return ResourceManager.GetString("dashboard_emptyexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses title is empty. Please insert any title (food, groceries, bills, entertainment, transfer, etc...).
        /// </summary>
        internal static string dashboard_emptytitle {
            get {
                return ResourceManager.GetString("dashboard_emptytitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error adding new expenses..
        /// </summary>
        internal static string dashboard_erroraddexp {
            get {
                return ResourceManager.GetString("dashboard_erroraddexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expenses added..
        /// </summary>
        internal static string dashboard_expadded {
            get {
                return ResourceManager.GetString("dashboard_expadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses deleted..
        /// </summary>
        internal static string dashboard_expdeleted {
            get {
                return ResourceManager.GetString("dashboard_expdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error deleting selected expenses..
        /// </summary>
        internal static string dashboard_expdeleteerror {
            get {
                return ResourceManager.GetString("dashboard_expdeleteerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses for today.
        /// </summary>
        internal static string dashboard_expfortoday {
            get {
                return ResourceManager.GetString("dashboard_expfortoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same as.
        /// </summary>
        internal static string dashboard_expsameas {
            get {
                return ResourceManager.GetString("dashboard_expsameas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses today is.
        /// </summary>
        internal static string dashboard_exptodayis {
            get {
                return ResourceManager.GetString("dashboard_exptodayis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,.
        /// </summary>
        internal static string dashboard_hi {
            get {
                return ResourceManager.GetString("dashboard_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string dashboard_infoincome {
            get {
                return ResourceManager.GetString("dashboard_infoincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string dashboard_infosummary {
            get {
                return ResourceManager.GetString("dashboard_infosummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Commitment.
        /// </summary>
        internal static string dashboard_infototalcomm {
            get {
                return ResourceManager.GetString("dashboard_infototalcomm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Expenses.
        /// </summary>
        internal static string dashboard_infototalexp {
            get {
                return ResourceManager.GetString("dashboard_infototalexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money spent today.
        /// </summary>
        internal static string dashboard_moneyspent {
            get {
                return ResourceManager.GetString("dashboard_moneyspent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Expenses.
        /// </summary>
        internal static string dashboard_noexp {
            get {
                return ResourceManager.GetString("dashboard_noexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no expenses for today..
        /// </summary>
        internal static string dashboard_noexpdesc {
            get {
                return ResourceManager.GetString("dashboard_noexpdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no record.
        /// </summary>
        internal static string dashboard_norecord {
            get {
                return ResourceManager.GetString("dashboard_norecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income not yet set. Update income at top-right button.
        /// </summary>
        internal static string dashboard_setincome {
            get {
                return ResourceManager.GetString("dashboard_setincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the money spent on ?.
        /// </summary>
        internal static string dashboard_spendon {
            get {
                return ResourceManager.GetString("dashboard_spendon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete.
        /// </summary>
        internal static string dashboard_suredel1 {
            get {
                return ResourceManager.GetString("dashboard_suredel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from today expenses ?.
        /// </summary>
        internal static string dashboard_suredel2 {
            get {
                return ResourceManager.GetString("dashboard_suredel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to than yesterday.
        /// </summary>
        internal static string dashboard_thanytd {
            get {
                return ResourceManager.GetString("dashboard_thanytd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string dashboard_today {
            get {
                return ResourceManager.GetString("dashboard_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is.
        /// </summary>
        internal static string dashboard_todayis {
            get {
                return ResourceManager.GetString("dashboard_todayis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string dashboard_total {
            get {
                return ResourceManager.GetString("dashboard_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string dashboard_ytd {
            get {
                return ResourceManager.GetString("dashboard_ytd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string dashobard_add {
            get {
                return ResourceManager.GetString("dashobard_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert income amount..
        /// </summary>
        internal static string exp_emptydesc {
            get {
                return ResourceManager.GetString("exp_emptydesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error updating income amount..
        /// </summary>
        internal static string exp_errorupdincome {
            get {
                return ResourceManager.GetString("exp_errorupdincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Income.
        /// </summary>
        internal static string exp_updateincome {
            get {
                return ResourceManager.GetString("exp_updateincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string intro_btnokay {
            get {
                return ResourceManager.GetString("intro_btnokay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip for now.
        /// </summary>
        internal static string intro_btnskip {
            get {
                return ResourceManager.GetString("intro_btnskip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        internal static string intro_fname {
            get {
                return ResourceManager.GetString("intro_fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account created yet.
        /// </summary>
        internal static string intro_line1 {
            get {
                return ResourceManager.GetString("intro_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create your username and password.
        /// </summary>
        internal static string intro_line2 {
            get {
                return ResourceManager.GetString("intro_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        internal static string intro_lname {
            get {
                return ResourceManager.GetString("intro_lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create your password.
        /// </summary>
        internal static string intro_password {
            get {
                return ResourceManager.GetString("intro_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string intro_welcome {
            get {
                return ResourceManager.GetString("intro_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not attach any pictures in Expenses or Commitment..
        /// </summary>
        internal static string media_alertdescnopic {
            get {
                return ResourceManager.GetString("media_alertdescnopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pictures.
        /// </summary>
        internal static string media_alerttitlenopic {
            get {
                return ResourceManager.GetString("media_alerttitlenopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        internal static string media_colcommitment {
            get {
                return ResourceManager.GetString("media_colcommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment of commitment(s).
        /// </summary>
        internal static string media_colcommitmentselected {
            get {
                return ResourceManager.GetString("media_colcommitmentselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string media_colexpenses {
            get {
                return ResourceManager.GetString("media_colexpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses on.
        /// </summary>
        internal static string media_colexpenseselected {
            get {
                return ResourceManager.GetString("media_colexpenseselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Gallery.
        /// </summary>
        internal static string media_navtitle {
            get {
                return ResourceManager.GetString("media_navtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no pictures.
        /// </summary>
        internal static string media_nopic {
            get {
                return ResourceManager.GetString("media_nopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        internal static string setting_apptheme {
            get {
                return ResourceManager.GetString("setting_apptheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string setting_currency {
            get {
                return ResourceManager.GetString("setting_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string setting_dark {
            get {
                return ResourceManager.GetString("setting_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.
        /// </summary>
        internal static string setting_dim {
            get {
                return ResourceManager.GetString("setting_dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string setting_editprofile {
            get {
                return ResourceManager.GetString("setting_editprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string setting_language {
            get {
                return ResourceManager.GetString("setting_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string setting_light {
            get {
                return ResourceManager.GetString("setting_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string setting_navbar {
            get {
                return ResourceManager.GetString("setting_navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string setting_selectlang {
            get {
                return ResourceManager.GetString("setting_selectlang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string setting_topright_created {
            get {
                return ResourceManager.GetString("setting_topright_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently login.
        /// </summary>
        internal static string setting_topright_current {
            get {
                return ResourceManager.GetString("setting_topright_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete My Account.
        /// </summary>
        internal static string setting_topright_delete {
            get {
                return ResourceManager.GetString("setting_topright_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string setting_topright_lastlogin {
            get {
                return ResourceManager.GetString("setting_topright_lastlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string setting_topright_okay {
            get {
                return ResourceManager.GetString("setting_topright_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account(s) on this device.
        /// </summary>
        internal static string setting_topright_title {
            get {
                return ResourceManager.GetString("setting_topright_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string setting_topright_updated {
            get {
                return ResourceManager.GetString("setting_topright_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string setting_version {
            get {
                return ResourceManager.GetString("setting_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string settupdate_cancel {
            get {
                return ResourceManager.GetString("settupdate_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio, tagline, quotes, etc....
        /// </summary>
        internal static string settupdate_descplaceholder {
            get {
                return ResourceManager.GetString("settupdate_descplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string settupdate_description {
            get {
                return ResourceManager.GetString("settupdate_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your image.
        /// </summary>
        internal static string settupdate_media {
            get {
                return ResourceManager.GetString("settupdate_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string settupdate_password {
            get {
                return ResourceManager.GetString("settupdate_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re-type your password.
        /// </summary>
        internal static string settupdate_retype {
            get {
                return ResourceManager.GetString("settupdate_retype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string settupdate_update {
            get {
                return ResourceManager.GetString("settupdate_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        internal static string sidemenu_commitment {
            get {
                return ResourceManager.GetString("sidemenu_commitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string sidemenu_dashboard {
            get {
                return ResourceManager.GetString("sidemenu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string sidemenu_expenses {
            get {
                return ResourceManager.GetString("sidemenu_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string sidemenu_gallery {
            get {
                return ResourceManager.GetString("sidemenu_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string sidemenu_logout {
            get {
                return ResourceManager.GetString("sidemenu_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string sidemenu_settings {
            get {
                return ResourceManager.GetString("sidemenu_settings", resourceCulture);
            }
        }
    }
}
