//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xperimen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xperimen.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string app_alert {
            get {
                return ResourceManager.GetString("app_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string app_cancel {
            get {
                return ResourceManager.GetString("app_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string app_confirm {
            get {
                return ResourceManager.GetString("app_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Password.
        /// </summary>
        internal static string app_confirmpwd {
            get {
                return ResourceManager.GetString("app_confirmpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string app_delete {
            get {
                return ResourceManager.GetString("app_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string app_error {
            get {
                return ResourceManager.GetString("app_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        internal static string app_exist {
            get {
                return ResourceManager.GetString("app_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string app_failed {
            get {
                return ResourceManager.GetString("app_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Match.
        /// </summary>
        internal static string app_notmatch {
            get {
                return ResourceManager.GetString("app_notmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string app_okay {
            get {
                return ResourceManager.GetString("app_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        internal static string app_permission {
            get {
                return ResourceManager.GetString("app_permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string app_success {
            get {
                return ResourceManager.GetString("app_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string app_unavailable {
            get {
                return ResourceManager.GetString("app_unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo cancelled..
        /// </summary>
        internal static string camgal_camcancel {
            get {
                return ResourceManager.GetString("camgal_camcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is not available or take photo not supported..
        /// </summary>
        internal static string camgal_camunavailable {
            get {
                return ResourceManager.GetString("camgal_camunavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No photo selected..
        /// </summary>
        internal static string camgal_nophotoselect {
            get {
                return ResourceManager.GetString("camgal_nophotoselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App required permission to access media gallery to pick photos..
        /// </summary>
        internal static string camgal_permmedia {
            get {
                return ResourceManager.GetString("camgal_permmedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App required permission to access photos to pick photos..
        /// </summary>
        internal static string camgal_permphoto {
            get {
                return ResourceManager.GetString("camgal_permphoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo gallery is not available to pick photo..
        /// </summary>
        internal static string camgal_photounavailable {
            get {
                return ResourceManager.GetString("camgal_photounavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account and all the data successfully deleted..
        /// </summary>
        internal static string code_setting_allsuccessdelete {
            get {
                return ResourceManager.GetString("code_setting_allsuccessdelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted..
        /// </summary>
        internal static string code_setting_deleted {
            get {
                return ResourceManager.GetString("code_setting_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with that username already exist. Please choose a different username..
        /// </summary>
        internal static string code_setting_edyexist {
            get {
                return ResourceManager.GetString("code_setting_edyexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error. Failed to delete this account..
        /// </summary>
        internal static string code_setting_faildelete {
            get {
                return ResourceManager.GetString("code_setting_faildelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error. Failed to delete the user..
        /// </summary>
        internal static string code_setting_faildeleteuser {
            get {
                return ResourceManager.GetString("code_setting_faildeleteuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty. Please insert your first name..
        /// </summary>
        internal static string code_setting_fnameempty {
            get {
                return ResourceManager.GetString("code_setting_fnameempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error. Current login ID not found..
        /// </summary>
        internal static string code_setting_idnotfound {
            get {
                return ResourceManager.GetString("code_setting_idnotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty. Please insert your last name..
        /// </summary>
        internal static string code_setting_lnameempty {
            get {
                return ResourceManager.GetString("code_setting_lnameempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current login information not found..
        /// </summary>
        internal static string code_setting_lognotfound {
            get {
                return ResourceManager.GetString("code_setting_lognotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated..
        /// </summary>
        internal static string code_setting_profupdated {
            get {
                return ResourceManager.GetString("code_setting_profupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty. Please insert your password..
        /// </summary>
        internal static string code_setting_pwdempty {
            get {
                return ResourceManager.GetString("code_setting_pwdempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be more than 6 characters..
        /// </summary>
        internal static string code_setting_pwdmore6 {
            get {
                return ResourceManager.GetString("code_setting_pwdmore6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password is not match with current password..
        /// </summary>
        internal static string code_setting_pwdnotmatch {
            get {
                return ResourceManager.GetString("code_setting_pwdnotmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-type your password..
        /// </summary>
        internal static string code_setting_retypepwd {
            get {
                return ResourceManager.GetString("code_setting_retypepwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you confirm to delete your account ? All data such as commitments and expenses will be deleted..
        /// </summary>
        internal static string code_setting_suredelself {
            get {
                return ResourceManager.GetString("code_setting_suredelself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete .
        /// </summary>
        internal static string code_setting_suredeluser {
            get {
                return ResourceManager.GetString("code_setting_suredeluser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update application theme failed..
        /// </summary>
        internal static string code_setting_themefailed {
            get {
                return ResourceManager.GetString("code_setting_themefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information failed..
        /// </summary>
        internal static string code_setting_updatefailed {
            get {
                return ResourceManager.GetString("code_setting_updatefailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be more than 6 characters..
        /// </summary>
        internal static string code_setting_usermore6 {
            get {
                return ResourceManager.GetString("code_setting_usermore6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create your username.
        /// </summary>
        internal static string code_setting_username {
            get {
                return ResourceManager.GetString("code_setting_username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be empty. Please insert your username..
        /// </summary>
        internal static string code_setting_usernameempty {
            get {
                return ResourceManager.GetString("code_setting_usernameempty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update expenses in the left side menu button.
        /// </summary>
        internal static string dashboard_editexp {
            get {
                return ResourceManager.GetString("dashboard_editexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses for today.
        /// </summary>
        internal static string dashboard_expfortoday {
            get {
                return ResourceManager.GetString("dashboard_expfortoday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same as.
        /// </summary>
        internal static string dashboard_expsameas {
            get {
                return ResourceManager.GetString("dashboard_expsameas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses today is.
        /// </summary>
        internal static string dashboard_exptodayis {
            get {
                return ResourceManager.GetString("dashboard_exptodayis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi,.
        /// </summary>
        internal static string dashboard_hi {
            get {
                return ResourceManager.GetString("dashboard_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no record.
        /// </summary>
        internal static string dashboard_norecord {
            get {
                return ResourceManager.GetString("dashboard_norecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income not yet set. Update income at top-right button.
        /// </summary>
        internal static string dashboard_setincome {
            get {
                return ResourceManager.GetString("dashboard_setincome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to than yesterday.
        /// </summary>
        internal static string dashboard_thanytd {
            get {
                return ResourceManager.GetString("dashboard_thanytd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string dashboard_today {
            get {
                return ResourceManager.GetString("dashboard_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today is.
        /// </summary>
        internal static string dashboard_todayis {
            get {
                return ResourceManager.GetString("dashboard_todayis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string dashboard_total {
            get {
                return ResourceManager.GetString("dashboard_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string dashboard_ytd {
            get {
                return ResourceManager.GetString("dashboard_ytd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string dashobard_add {
            get {
                return ResourceManager.GetString("dashobard_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string intro_btnokay {
            get {
                return ResourceManager.GetString("intro_btnokay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip for now.
        /// </summary>
        internal static string intro_btnskip {
            get {
                return ResourceManager.GetString("intro_btnskip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        internal static string intro_fname {
            get {
                return ResourceManager.GetString("intro_fname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No account created yet.
        /// </summary>
        internal static string intro_line1 {
            get {
                return ResourceManager.GetString("intro_line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create your username and password.
        /// </summary>
        internal static string intro_line2 {
            get {
                return ResourceManager.GetString("intro_line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name.
        /// </summary>
        internal static string intro_lname {
            get {
                return ResourceManager.GetString("intro_lname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create your password.
        /// </summary>
        internal static string intro_password {
            get {
                return ResourceManager.GetString("intro_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string intro_welcome {
            get {
                return ResourceManager.GetString("intro_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not attach any pictures in Expenses or Commitment..
        /// </summary>
        internal static string media_alertdescnopic {
            get {
                return ResourceManager.GetString("media_alertdescnopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pictures.
        /// </summary>
        internal static string media_alerttitlenopic {
            get {
                return ResourceManager.GetString("media_alerttitlenopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        internal static string media_colcommitment {
            get {
                return ResourceManager.GetString("media_colcommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment of commitment(s).
        /// </summary>
        internal static string media_colcommitmentselected {
            get {
                return ResourceManager.GetString("media_colcommitmentselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string media_colexpenses {
            get {
                return ResourceManager.GetString("media_colexpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses on.
        /// </summary>
        internal static string media_colexpenseselected {
            get {
                return ResourceManager.GetString("media_colexpenseselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Gallery.
        /// </summary>
        internal static string media_navtitle {
            get {
                return ResourceManager.GetString("media_navtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no pictures.
        /// </summary>
        internal static string media_nopic {
            get {
                return ResourceManager.GetString("media_nopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        internal static string setting_apptheme {
            get {
                return ResourceManager.GetString("setting_apptheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string setting_currency {
            get {
                return ResourceManager.GetString("setting_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string setting_dark {
            get {
                return ResourceManager.GetString("setting_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dim.
        /// </summary>
        internal static string setting_dim {
            get {
                return ResourceManager.GetString("setting_dim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string setting_editprofile {
            get {
                return ResourceManager.GetString("setting_editprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string setting_language {
            get {
                return ResourceManager.GetString("setting_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string setting_light {
            get {
                return ResourceManager.GetString("setting_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string setting_navbar {
            get {
                return ResourceManager.GetString("setting_navbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string setting_topright_created {
            get {
                return ResourceManager.GetString("setting_topright_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently login.
        /// </summary>
        internal static string setting_topright_current {
            get {
                return ResourceManager.GetString("setting_topright_current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete My Account.
        /// </summary>
        internal static string setting_topright_delete {
            get {
                return ResourceManager.GetString("setting_topright_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Login.
        /// </summary>
        internal static string setting_topright_lastlogin {
            get {
                return ResourceManager.GetString("setting_topright_lastlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string setting_topright_okay {
            get {
                return ResourceManager.GetString("setting_topright_okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account(s) on this device.
        /// </summary>
        internal static string setting_topright_title {
            get {
                return ResourceManager.GetString("setting_topright_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string setting_topright_updated {
            get {
                return ResourceManager.GetString("setting_topright_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string setting_version {
            get {
                return ResourceManager.GetString("setting_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string settupdate_cancel {
            get {
                return ResourceManager.GetString("settupdate_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio, tagline, quotes, etc....
        /// </summary>
        internal static string settupdate_descplaceholder {
            get {
                return ResourceManager.GetString("settupdate_descplaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string settupdate_description {
            get {
                return ResourceManager.GetString("settupdate_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update your image.
        /// </summary>
        internal static string settupdate_media {
            get {
                return ResourceManager.GetString("settupdate_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string settupdate_password {
            get {
                return ResourceManager.GetString("settupdate_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re-type your password.
        /// </summary>
        internal static string settupdate_retype {
            get {
                return ResourceManager.GetString("settupdate_retype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string settupdate_update {
            get {
                return ResourceManager.GetString("settupdate_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment.
        /// </summary>
        internal static string sidemenu_commitment {
            get {
                return ResourceManager.GetString("sidemenu_commitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string sidemenu_dashboard {
            get {
                return ResourceManager.GetString("sidemenu_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string sidemenu_expenses {
            get {
                return ResourceManager.GetString("sidemenu_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string sidemenu_gallery {
            get {
                return ResourceManager.GetString("sidemenu_gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string sidemenu_logout {
            get {
                return ResourceManager.GetString("sidemenu_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string sidemenu_settings {
            get {
                return ResourceManager.GetString("sidemenu_settings", resourceCulture);
            }
        }
    }
}
